- name: Ensure group "dev-team" exists
  group:
    name: dev-team
    state: present

- name: Create the user 'jaywon'
  user:
    name: jaywon
    shell: /bin/bash
    password: $6$ywsmNgg54uveb1I8$UNUzewUghRAqtMPiX6Nz2ViJ5nLPcUrfH8rhFPFcbfbmNJ/t/7PTzD5nwJ/3/trk0xHAgJLZd5WKF.OEOlv5Y/
    append: yes

- name: Assign 'jaywon' to the 'dev-team' group
  user:
    name: jaywon
    groups: dev-team
    append: yes

- name: Create a directory named 'engineering'
  file:
    path: /opt/engineering
    state: directory
    owner: root
    group: dev-team
    mode: '0750'

# - name: Force user 'jaywon' to change password on first login
#   command: chage -d 0 jaywon

- name: Create a file inside the 'engineering' directory
  file:
    path: "/opt/engineering/private-info.txt"
    state: touch
    owner: jaywon
    group: dev-team
    mode: '0770'